# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/palman/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/palman/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/lge/palman/proprietary/bin/bridgemgrd:systembin/bridgemgrd/bin/bridgemgrd \
    vendor/lge/palman/proprietary/bin/btnvtool:systembin/btnvtool/bin/btnvtool \
    vendor/lge/palman/proprietary/bin/ds_fmc_appd:systembin/ds_fmc_appd/bin/ds_fmc_appd \
    vendor/lge/palman/proprietary/bin/efsks:systembin/efsks/bin/efsks \
    vendor/lge/palman/proprietary/bin/hci_qcomm_init:systembin/hci_qcomm_init/bin/hci_qcomm_init \
    vendor/lge/palman/proprietary/bin/ks:systembin/ks/bin/ks \
    vendor/lge/palman/proprietary/bin/mm-qcamera-daemon:systembin/mm-qcamera-daemon/bin/mm-qcamera-daemon \
    vendor/lge/palman/proprietary/bin/mpdecision:systembin/mpdecision/bin/mpdecision \
    vendor/lge/palman/proprietary/bin/netmgrd:systembin/netmgrd/bin/netmgrd \
    vendor/lge/palman/proprietary/bin/port-bridge:systembin/port-bridge/bin/port-bridge \
    vendor/lge/palman/proprietary/bin/qcks:systembin/qcks/bin/qcks \
    vendor/lge/palman/proprietary/bin/qmuxd:systembin/qmuxd/bin/qmuxd \
    vendor/lge/palman/proprietary/bin/qseecomd:systembin/qseecomd/bin/qseecomd \
    vendor/lge/palman/proprietary/bin/radish:systembin/radish/bin/radish \
    vendor/lge/palman/proprietary/bin/rmt_storage:systembin/rmt_storage/bin/rmt_storage \
    vendor/lge/palman/proprietary/bin/sensors.qcom:systembin/sensors.qcom/bin/sensors.qcom \
    vendor/lge/palman/proprietary/bin/thermald:systembin/thermald/bin/thermald \
    vendor/lge/palman/proprietary/bin/time_daemon:systembin/time_daemon/bin/time_daemon \
    vendor/lge/palman/proprietary/etc/firmware/vidc.b00:systemetc/firmware/vidc.b00/etc/firmware/vidc.b00 \
    vendor/lge/palman/proprietary/etc/firmware/vidc.b01:systemetc/firmware/vidc.b01/etc/firmware/vidc.b01 \
    vendor/lge/palman/proprietary/etc/firmware/vidc.b02:systemetc/firmware/vidc.b02/etc/firmware/vidc.b02 \
    vendor/lge/palman/proprietary/etc/firmware/vidc.b03:systemetc/firmware/vidc.b03/etc/firmware/vidc.b03 \
    vendor/lge/palman/proprietary/etc/firmware/vidc.mdt:systemetc/firmware/vidc.mdt/etc/firmware/vidc.mdt \
    vendor/lge/palman/proprietary/etc/firmware/vidc_1080p.fw:systemetc/firmware/vidc_1080p.fw/etc/firmware/vidc_1080p.fw \
    vendor/lge/palman/proprietary/lib/hw/camera.msm8960.so:systemlib/hw/camera.msm8960.so/lib/hw/camera.msm8960.so \
    vendor/lge/palman/proprietary/lib/hw/gps.msm8960.so:systemlib/hw/gps.msm8960.so/lib/hw/gps.msm8960.so \
    vendor/lge/palman/proprietary/lib/hw/sensors.msm8960.so:systemlib/hw/sensors.msm8960.so/lib/hw/sensors.msm8960.so \
    vendor/lge/palman/proprietary/lib/libAKM.so:systemlib/libAKM.so/lib/libAKM.so \
    vendor/lge/palman/proprietary/lib/libCommandSvc.so:systemlib/libCommandSvc.so/lib/libCommandSvc.so \
    vendor/lge/palman/proprietary/lib/libHDR.so:systemlib/libHDR.so/lib/libHDR.so \
    vendor/lge/palman/proprietary/lib/libQSEEComAPI.so:systemlib/libQSEEComAPI.so/lib/libQSEEComAPI.so \
    vendor/lge/palman/proprietary/lib/libacdbloader.so:systemlib/libacdbloader.so/lib/libacdbloader.so \
    vendor/lge/palman/proprietary/lib/libadsprpc.so:systemlib/libadsprpc.so/lib/libadsprpc.so \
    vendor/lge/palman/proprietary/lib/libaudcal.so:systemlib/libaudcal.so/lib/libaudcal.so \
    vendor/lge/palman/proprietary/lib/libaudioalsa.so:systemlib/libaudioalsa.so/lib/libaudioalsa.so \
    vendor/lge/palman/proprietary/lib/libchromatix_imx111_default_video.so:systemlib/libchromatix_imx111_default_video.so/lib/libchromatix_imx111_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_imx111_preview.so:systemlib/libchromatix_imx111_preview.so/lib/libchromatix_imx111_preview.so \
    vendor/lge/palman/proprietary/lib/libchromatix_imx111_zsl.so:systemlib/libchromatix_imx111_zsl.so/lib/libchromatix_imx111_zsl.so \
    vendor/lge/palman/proprietary/lib/libchromatix_imx119_default_video.so:systemlib/libchromatix_imx119_default_video.so/lib/libchromatix_imx119_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_imx119_preview.so:systemlib/libchromatix_imx119_preview.so/lib/libchromatix_imx119_preview.so \
    vendor/lge/palman/proprietary/lib/libchromatix_imx119_vt.so:systemlib/libchromatix_imx119_vt.so/lib/libchromatix_imx119_vt.so \
    vendor/lge/palman/proprietary/lib/libchromatix_mt9e013_default_video.so:systemlib/libchromatix_mt9e013_default_video.so/lib/libchromatix_mt9e013_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_mt9e013_preview.so:systemlib/libchromatix_mt9e013_preview.so/lib/libchromatix_mt9e013_preview.so \
    vendor/lge/palman/proprietary/lib/libchromatix_mt9e013_video_hfr.so:systemlib/libchromatix_mt9e013_video_hfr.so/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/lge/palman/proprietary/lib/libchromatix_ov5647_default_video.so:systemlib/libchromatix_ov5647_default_video.so/lib/libchromatix_ov5647_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_ov5647_preview.so:systemlib/libchromatix_ov5647_preview.so/lib/libchromatix_ov5647_preview.so \
    vendor/lge/palman/proprietary/lib/libchromatix_ov5647_video_hfr.so:systemlib/libchromatix_ov5647_video_hfr.so/lib/libchromatix_ov5647_video_hfr.so \
    vendor/lge/palman/proprietary/lib/libchromatix_ov8825_default_video.so:systemlib/libchromatix_ov8825_default_video.so/lib/libchromatix_ov8825_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_ov8825_preview.so:systemlib/libchromatix_ov8825_preview.so/lib/libchromatix_ov8825_preview.so \
    vendor/lge/palman/proprietary/lib/libchromatix_ov9726_default_video.so:systemlib/libchromatix_ov9726_default_video.so/lib/libchromatix_ov9726_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_ov9726_preview.so:systemlib/libchromatix_ov9726_preview.so/lib/libchromatix_ov9726_preview.so \
    vendor/lge/palman/proprietary/lib/libchromatix_s5k4e1_default_video.so:systemlib/libchromatix_s5k4e1_default_video.so/lib/libchromatix_s5k4e1_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_s5k4e1_preview.so:systemlib/libchromatix_s5k4e1_preview.so/lib/libchromatix_s5k4e1_preview.so \
    vendor/lge/palman/proprietary/lib/libchromatix_s5k4e5ya_default_video.so:systemlib/libchromatix_s5k4e5ya_default_video.so/lib/libchromatix_s5k4e5ya_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_s5k4e5ya_preview.so:systemlib/libchromatix_s5k4e5ya_preview.so/lib/libchromatix_s5k4e5ya_preview.so \
    vendor/lge/palman/proprietary/lib/libchromatix_s5k4e5ya_zsl.so:systemlib/libchromatix_s5k4e5ya_zsl.so/lib/libchromatix_s5k4e5ya_zsl.so \
    vendor/lge/palman/proprietary/lib/libchromatix_vx6953_default_video.so:systemlib/libchromatix_vx6953_default_video.so/lib/libchromatix_vx6953_default_video.so \
    vendor/lge/palman/proprietary/lib/libchromatix_vx6953_preview.so:systemlib/libchromatix_vx6953_preview.so/lib/libchromatix_vx6953_preview.so \
    vendor/lge/palman/proprietary/lib/libconfigdb.so:systemlib/libconfigdb.so/lib/libconfigdb.so \
    vendor/lge/palman/proprietary/lib/libcsd-client.so:systemlib/libcsd-client.so/lib/libcsd-client.so \
    vendor/lge/palman/proprietary/lib/libdiag.so:systemlib/libdiag.so/lib/libdiag.so \
    vendor/lge/palman/proprietary/lib/libdrmdiag.so:systemlib/libdrmdiag.so/lib/libdrmdiag.so \
    vendor/lge/palman/proprietary/lib/libdrmfs.so:systemlib/libdrmfs.so/lib/libdrmfs.so \
    vendor/lge/palman/proprietary/lib/libdrmtime.so:systemlib/libdrmtime.so/lib/libdrmtime.so \
    vendor/lge/palman/proprietary/lib/libdsi_netctrl.so:systemlib/libdsi_netctrl.so/lib/libdsi_netctrl.so \
    vendor/lge/palman/proprietary/lib/libdss.so:systemlib/libdss.so/lib/libdss.so \
    vendor/lge/palman/proprietary/lib/libdsutils.so:systemlib/libdsutils.so/lib/libdsutils.so \
    vendor/lge/palman/proprietary/lib/libgemini.so:systemlib/libgemini.so/lib/libgemini.so \
    vendor/lge/palman/proprietary/lib/libgeofence.so:systemlib/libgeofence.so/lib/libgeofence.so \
    vendor/lge/palman/proprietary/lib/libgps.utils.so:systemlib/libgps.utils.so/lib/libgps.utils.so \
    vendor/lge/palman/proprietary/lib/libidl.so:systemlib/libidl.so/lib/libidl.so \
    vendor/lge/palman/proprietary/lib/libimage-jpeg-enc-omx-comp.so:systemlib/libimage-jpeg-enc-omx-comp.so/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/lge/palman/proprietary/lib/libimage-omx-common.so:systemlib/libimage-omx-common.so/lib/libimage-omx-common.so \
    vendor/lge/palman/proprietary/lib/libloc_adapter.so:systemlib/libloc_adapter.so/lib/libloc_adapter.so \
    vendor/lge/palman/proprietary/lib/libloc_api_v02.so:systemlib/libloc_api_v02.so/lib/libloc_api_v02.so \
    vendor/lge/palman/proprietary/lib/libloc_eng.so:systemlib/libloc_eng.so/lib/libloc_eng.so \
    vendor/lge/palman/proprietary/lib/libmercury.so:systemlib/libmercury.so/lib/libmercury.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_3a_legacy.so:systemlib/libmmcamera_3a_legacy.so/lib/libmmcamera_3a_legacy.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_faceproc.so:systemlib/libmmcamera_faceproc.so/lib/libmmcamera_faceproc.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_frameproc.so:systemlib/libmmcamera_frameproc.so/lib/libmmcamera_frameproc.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_hdr_lib.so:systemlib/libmmcamera_hdr_lib.so/lib/libmmcamera_hdr_lib.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_image_stab.so:systemlib/libmmcamera_image_stab.so/lib/libmmcamera_image_stab.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_interface.so:systemlib/libmmcamera_interface.so/lib/libmmcamera_interface.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_plugin.so:systemlib/libmmcamera_plugin.so/lib/libmmcamera_plugin.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_statsproc31.so:systemlib/libmmcamera_statsproc31.so/lib/libmmcamera_statsproc31.so \
    vendor/lge/palman/proprietary/lib/libmmcamera_wavelet_lib.so:systemlib/libmmcamera_wavelet_lib.so/lib/libmmcamera_wavelet_lib.so \
    vendor/lge/palman/proprietary/lib/libmmjpeg_interface.so:systemlib/libmmjpeg_interface.so/lib/libmmjpeg_interface.so \
    vendor/lge/palman/proprietary/lib/libmmstillomx.so:systemlib/libmmstillomx.so/lib/libmmstillomx.so \
    vendor/lge/palman/proprietary/lib/libmorpho_noise_reduction.so:systemlib/libmorpho_noise_reduction.so/lib/libmorpho_noise_reduction.so \
    vendor/lge/palman/proprietary/lib/libnetmgr.so:systemlib/libnetmgr.so/lib/libnetmgr.so \
    vendor/lge/palman/proprietary/lib/liboemcamera.so:systemlib/liboemcamera.so/lib/liboemcamera.so \
    vendor/lge/palman/proprietary/lib/libqcci_legacy.so:systemlib/libqcci_legacy.so/lib/libqcci_legacy.so \
    vendor/lge/palman/proprietary/lib/libqdi.so:systemlib/libqdi.so/lib/libqdi.so \
    vendor/lge/palman/proprietary/lib/libqdp.so:systemlib/libqdp.so/lib/libqdp.so \
    vendor/lge/palman/proprietary/lib/libqmi.so:systemlib/libqmi.so/lib/libqmi.so \
    vendor/lge/palman/proprietary/lib/libqmi_cci.so:systemlib/libqmi_cci.so/lib/libqmi_cci.so \
    vendor/lge/palman/proprietary/lib/libqmi_client_qmux.so:systemlib/libqmi_client_qmux.so/lib/libqmi_client_qmux.so \
    vendor/lge/palman/proprietary/lib/libqmi_common_so.so:systemlib/libqmi_common_so.so/lib/libqmi_common_so.so \
    vendor/lge/palman/proprietary/lib/libqmi_csi.so:systemlib/libqmi_csi.so/lib/libqmi_csi.so \
    vendor/lge/palman/proprietary/lib/libqmi_csvt_srvc.so:systemlib/libqmi_csvt_srvc.so/lib/libqmi_csvt_srvc.so \
    vendor/lge/palman/proprietary/lib/libqmi_encdec.so:systemlib/libqmi_encdec.so/lib/libqmi_encdec.so \
    vendor/lge/palman/proprietary/lib/libqmiservices.so:systemlib/libqmiservices.so/lib/libqmiservices.so \
    vendor/lge/palman/proprietary/lib/libril-qc-qmi-1.so:systemlib/libril-qc-qmi-1.so/lib/libril-qc-qmi-1.so \
    vendor/lge/palman/proprietary/lib/libril-qcril-hook-oem.so:systemlib/libril-qcril-hook-oem.so/lib/libril-qcril-hook-oem.so \
    vendor/lge/palman/proprietary/lib/libril.so:systemlib/libril.so/lib/libril.so \
    vendor/lge/palman/proprietary/lib/libsensor1.so:systemlib/libsensor1.so/lib/libsensor1.so \
    vendor/lge/palman/proprietary/lib/libsensor_reg.so:systemlib/libsensor_reg.so/lib/libsensor_reg.so \
    vendor/lge/palman/proprietary/lib/libsensor_user_cal.so:systemlib/libsensor_user_cal.so/lib/libsensor_user_cal.so \
    vendor/lge/palman/proprietary/lib/libtime_genoff.so:systemlib/libtime_genoff.so/lib/libtime_genoff.so \
    vendor/lge/palman/proprietary/lib/libxml.so:systemlib/libxml.so/lib/libxml.so \
    vendor/lge/palman/proprietary/vendor/firmware/a300_pfp.fw:systemvendor/firmware/a300_pfp.fw/vendor/firmware/a300_pfp.fw \
    vendor/lge/palman/proprietary/vendor/firmware/a300_pm4.fw:systemvendor/firmware/a300_pm4.fw/vendor/firmware/a300_pm4.fw \
    vendor/lge/palman/proprietary/vendor/lib/egl/eglsubAndroid.so:systemvendor/lib/egl/eglsubAndroid.so/vendor/lib/egl/eglsubAndroid.so \
    vendor/lge/palman/proprietary/vendor/lib/egl/libEGL_adreno.so:systemvendor/lib/egl/libEGL_adreno.so/vendor/lib/egl/libEGL_adreno.so \
    vendor/lge/palman/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:systemvendor/lib/egl/libGLESv1_CM_adreno.so/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/lge/palman/proprietary/vendor/lib/egl/libGLESv2_adreno.so:systemvendor/lib/egl/libGLESv2_adreno.so/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/lge/palman/proprietary/vendor/lib/egl/libplayback_adreno.so:systemvendor/lib/egl/libplayback_adreno.so/vendor/lib/egl/libplayback_adreno.so \
    vendor/lge/palman/proprietary/vendor/lib/egl/libq3dtools_adreno.so:systemvendor/lib/egl/libq3dtools_adreno.so/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/lge/palman/proprietary/vendor/lib/libC2D2.so:systemvendor/lib/libC2D2.so/vendor/lib/libC2D2.so \
    vendor/lge/palman/proprietary/vendor/lib/libCB.so:systemvendor/lib/libCB.so/vendor/lib/libCB.so \
    vendor/lge/palman/proprietary/vendor/lib/libRSDriver_adreno.so:systemvendor/lib/libRSDriver_adreno.so/vendor/lib/libRSDriver_adreno.so \
    vendor/lge/palman/proprietary/vendor/lib/libadreno_utils.so:systemvendor/lib/libadreno_utils.so/vendor/lib/libadreno_utils.so \
    vendor/lge/palman/proprietary/vendor/lib/libc2d30-a3xx.so:systemvendor/lib/libc2d30-a3xx.so/vendor/lib/libc2d30-a3xx.so \
    vendor/lge/palman/proprietary/vendor/lib/libc2d30.so:systemvendor/lib/libc2d30.so/vendor/lib/libc2d30.so \
    vendor/lge/palman/proprietary/vendor/lib/libgsl.so:systemvendor/lib/libgsl.so/vendor/lib/libgsl.so \
    vendor/lge/palman/proprietary/vendor/lib/libmmjpeg.so:systemvendor/lib/libmmjpeg.so/vendor/lib/libmmjpeg.so \
    vendor/lge/palman/proprietary/vendor/lib/librs_adreno.so:systemvendor/lib/librs_adreno.so/vendor/lib/librs_adreno.so \
    vendor/lge/palman/proprietary/vendor/lib/librs_adreno_sha1.so:systemvendor/lib/librs_adreno_sha1.so/vendor/lib/librs_adreno_sha1.so \
    vendor/lge/palman/proprietary/vendor/lib/libsc-a3xx.so:systemvendor/lib/libsc-a3xx.so/vendor/lib/libsc-a3xx.so
